### PR TITLE
Issue #419: Compatibility with MySQL on alternate port

### LINKED ISSUE #419: DB/SQL Commands - Compatibility with MySQL on alternate port
# Steps to reproduce

* Install PHP and MySQL
* Ensure MySQL runs on an alternate port (_not_ `3306`; perhaps `3307` or `3333`)
* Install Backdrop, eg
    ```
    ./core/scripts/install.sh --db-url="mysql://myuser:mypass@127.0.0.1:3307/mydb" ...
    ```
* Run commands like `bee users` and `bee sql`

# Expected Results

* `bee users` -- Show list of users
* `bee sql` -- Open MySQL console

# Actual Results

* :green_circle:  `bee users` -- Show list of users
    ```
    | User ID | Username | Email             | Roles                | Last Login          | Status |
    | 1       | admin    | admin@example.com | administrator        | 01/08/2024 - 7:10pm | Active |
    ```

* :red_circle: `bee sql` -- Failure:
    ```
    ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
    ```

# Comments

So this is not a general framework problem. (The DB URL already supports port numbers.) It's just a problem the `sql` command -- where it transmits the DSN to MySQL CLI. The process relies on a stub file (`my.cnf` format) which is missing connection details.

### PR DESCRIPTION
**Pull request by totten**
Fixes #419

### CODE REVIEW

**Comment by yorkshire-pudding** [comment]
Hi @totten - please follow the Contributing guidelines - see https://github.com/backdrop-contrib/bee/wiki/Contributing or https://github.com/backdrop-contrib/bee/blob/1.x-1.x/CONTRIBUTING.md

**Comment by totten** [comment]
@yorkshire-pudding ok, the corresponding issue is #419 

Aside: I didn't try adding an automated-test for this because it's essentially an environment issue. It's quite rare for a PHP test-harnesses to provide a clean way to control this part of the environment.

**Comment by yorkshire-pudding** [comment]
@totten - thanks for creating the issue.  One other thing to do; in the description of this PR (starts with Overview), edit, delete what's there and add:
`Fixes #419`

That will link this request to the issue.

I think you are right that there is no real need for automated tests for this and it would be hard to do, so don't worry about that. I will try and test locally manually.

For now, I'll run the automated tests to check it doesn't break anything.

**Review by yorkshire-pudding — APPROVED** [review]
Look good. Thanks @totten

**Pull request merged**
